#!/usr/bin/env ansible-playbook
---

- name: containers | Create directory for containers
  file:
    state: directory
    path: /srv/containers
    mode: 0755

- name: containers | Copy Container Directory
  synchronize:
    src: "containers/"
    dest: "/srv/containers"
    archive: no
    checksum: no
    rsync_opts:
      - "-avhPx"

- name: containers | Get List of Containers
  shell: "ls -1 /srv/containers"
  # find:
  #   paths: /srv/containers
  #   patterns: "*"
  register: container_list


# - name: containers | Build Containers
#   shell: |
#     docker build \
#       --compress \
#       --force-rm \
#       --platform=linux/arm64 \
#       --file Dockerfile \
#       --tag "{{ item }}-arm64" \
#     ./{{ item }}
#   with_items: "{{ container_list.stdout_lines }}"


#########################################
## Containers
# - name: containers | Pull Containers
#   shell: >
#     docker pull \
#       --platform linux/arm64 \
#       {{ item.name }}
#   loop:
#     - name: busybox:latest


# - name: containers | Export container images
#   shell: >
#     docker save \
#       --output /srv/containers/{{ item.name }}.tar \
#       {{ item.name }}:{{item.tag}}
#   loop:
#     - name: busybox
#       tag:  latest


# - name: containers | Remove container images
#   shell: >
#     docker rmi $(docker images -aq)


# - name: containers | Load container images
#   shell: >
#     docker load \
#       --input /srv/containers/{{ item.name }}.tar
#   loop:
#     - name: busybox
#       tag:  local


# - name: containers | Run container images
#   shell: >
#     docker run \
#       -d \
#       --rm \
#       --name {{ item.name }} \
#       {{ item.name }}:{{item.tag}}
#   loop:
#     - name: busybox
#       tag:  latest


# NOTES
#
# https://www.redhat.com/sysadmin/container-images-ansible
# https://docs.ansible.com/ansible/2.8/scenario_guides/guide_docker.html
# https://docs.docker.com/registry/deploying/
#
#iptables -t nat -I POSTROUTING -p all -s 172.20.128.2 ! -d 172.20.128.2 -j SNAT --to-source YourInterfaceIP

...
