# {{ ansible_managed }}
network:
    version: 2
    renderer: networkd
    # Renderer can be 'networkd' or 'NetworkManager'
    ethernets:
        eth0:
            optional: true
            dhcp4: false
            addresses:
                - 10.0.0.1/24
            gateway4: 10.0.0.1
            nameservers:
                addresses:
                    - 10.0.0.1
            routes:
                - to: 0.0.0.0/0
                  via: 10.0.0.1
            #set-name: eth0