#!/usr/bin/env ansible-playbook
---

- name: enable-cgroup | Required
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
  register: cgroup_features

- name:  enable-cgroup | Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cgroup_features is changed

- name:  enable-cgroup | Wait for host
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cgroup_features is changed

...
