---

all:
  hosts:
    controller:
      ip:           192.168.1.162
      access_ip:    192.168.1.162
      ansible_host: 192.168.1.162
      ansible_user: ubuntu
      ansible_pass: ubuntu
      ansible_connection: ssh
      ansible_ssh_port:   22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa

  children:
    # workers:
    cluster:
      hosts:
        controller:

...
