#!/usr/bin/env ansible-playbook
---

- name: containers | Create directory for containers
  file:
    state: directory
    path: /srv/containers
    mode: 0755

- name: containers | Copy Container Directory
  synchronize:
    src: "containers/"
    dest: "/srv/containers"
    archive: no
    checksum: no
    rsync_opts:
      - "-avhPx"

- name: containers | Get List of Containers
  shell: "ls -1 /srv/containers"
  # find:
  #   paths: /srv/containers
  #   patterns: "*"
  register: container_list


# - name: containers | Build Containers
#   shell: |
#     docker build \
#       --compress \
#       --force-rm \
#       --platform=linux/arm64 \
#       --file Dockerfile \
#       --tag "{{ item }}-arm64" \
#     ./{{ item }}
#   with_items: "{{ container_list.stdout_lines }}"


...
