#!/usr/bin/env ansible-playbook
---

### sensible ###
# - name: Controller
# - description: >
#     Run the controller playbook.
# - index: 21
# - vars:
#   - config: /path/to/config.yml
#   - inventory: /path/to/inventory.yml
# - tags:
#   - controller
### /sensible ###

- name: "Control Node"
  hosts: controller
  gather_facts: true

  pre_tasks:
    - name: controller | Set Facts
      set_fact:
        host: "{{ controller }}"


  roles:
    # Common Roles
    - { role: common, become: true }
    - { role: disable-swap, become: true }
    - { role: docker, become: true }

    # Controller Roles
    - { role: controller, become: true }
    - { role: dnsmasq, become: true }


  tasks:
    - name: controller | Scan for connected Hosts
      import_role:
        name: discover
        tasks_from: main.yml


  post_tasks:
    - name: "Host Facts"
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 2

...
