---

all:
  hosts:
    controller:
      ip:           {{}}
      access_ip:    {{}}
      ansible_host: {{}}
      ansible_user: ubuntu
      ansible_pass: ubuntu
      ansible_connection: ssh
      ansible_ssh_port:   22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa

  children:
    # workers:
    #   ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@{{}}"'
    cluster:
      hosts:
        controller:

...
