#!/usr/bin/env ansible-playbook
---

# NOTE: chmod +x before running this script
#   $ chmod +x patch-ubuntu-image.yml
#   $ ./patch-ubuntu-image.yml

- name:         Patch Ubuntu Image
  hosts:        localhost
  connection:   local
  gather_facts: false

  vars_prompt:
    - name: "boot_path"
      prompt: "Path to 'system-boot' on micro SD device: "
      default: /media/chris/system-boot


  tasks:
    # Patch: Do not require password change for first login.
    - name: Patch 'user-data' (preserve whitespace)
      lineinfile:
        path: "{{ boot_path }}/user-data"
        state: present
        backup: no
        backrefs: yes
        regexp: '^(\s*)[#]?{{ item.search }}(: )*'
        line: '\1{{ item.replace }}'
      with_items:
        - { search: 'expire: true', replace: 'expire: false' }


    - name: Patch 'cmdline.txt' (Enable cgroups)
      replace:
        path: "{{ boot_path }}/cmdline.txt"
        regexp: '(\srootfstype=ext4)(\srootwait)'
        replace: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1\2'


    - name: Patch 'config.txt'
      lineinfile:
        path: "{{ boot_path }}/config.txt"
        state: present
        backup: no
        insertafter:
        line: |

          # Disable Wifi & Bluetooth
          [pi3]
          dtoverlay=disable-wifi
          dtoverlay=disable-bluetooth

...
