#!/usr/bin/env ansible-playbook
---

#########################################
## Network Scan
- name: discover | Scan Cluster Network for Hosts
  become: true
  block:
    - name: discover | Network Scan
      include_tasks: scan.yml

    - name: discover | Update Inventory
      include_tasks: join.yml

...
